INSERT INTO DIVISI VALUES ('SRT1', 'KRAI', 'Kontes Robot Abu Indonesia');
INSERT INTO DIVISI VALUES ('SRT2', 'KRSRI', 'Kontes Robot SAR Indonesia');
INSERT INTO DIVISI VALUES ('SRT3', 'KRTMI', 'Kontes Robot Tematik Indonesia');
INSERT INTO DIVISI VALUES ('SRT4', 'KRTI-FW', 'Kontes Robot Terbang Indonesia Fixed-Wings');
INSERT INTO DIVISI VALUES ('SRT5', 'KRTI-RP', 'Kontes Robot Terbang Indonesia Racing Plane');

INSERT INTO SUB_DIVISI VALUES ('SUB1', 'Mekanik');
INSERT INTO SUB_DIVISI VALUES ('SUB2', 'Elektronik');
INSERT INTO SUB_DIVISI VALUES ('SUB3', 'Programmer');
INSERT INTO SUB_DIVISI VALUES ('SUB4', 'System');

INSERT INTO ANGGOTA VALUES ('101', 'Rafif','H1D023008', 'SRT2', 'SUB1');
INSERT INTO ANGGOTA VALUES ('102', 'Athallah', 'H1D023013', 'SRT1', 'SUB3');
INSERT INTO ANGGOTA VALUES ('103', 'Bagus', 'H1D023042', 'SRT3', 'SUB1');
INSERT INTO ANGGOTA VALUES ('104', 'Rizki', 'H1D023067', 'SRT4', 'SUB4');


INSERT INTO JENIS_BARANG VALUES ('JBR01', 'Mekanik Produksi');
INSERT INTO JENIS_BARANG VALUES ('JBR02', 'Inventaris Umum');
INSERT INTO JENIS_BARANG VALUES ('JBR03', 'Elektronik');
INSERT INTO JENIS_BARANG VALUES ('JBR04', 'Mikrokontroler');

INSERT INTO BARANG VALUES ('BR001', 'Bor Tangan', 2, 7, 15000, 'JBR01');
INSERT INTO BARANG VALUES ('BR002', 'Kipas Angin', 4, 4, 5000, 'JBR02');
INSERT INTO BARANG VALUES ('BR003', 'Multimeter', 3, 5, 7000, 'JBR03');
INSERT INTO BARANG VALUES ('BR004', 'Arduino Uno', 5, 12, 10000, 'JBR04');

EXECUTE pinjam('102', 'BR004', 1);
EXECUTE kembali('102', 'BR004', '03-JUN-24 12.01.51.464000 AM');
    
EXECUTE pemasukkan('SRT1', 500000, 'Uang Donasi dari alumni');
EXECUTE pengeluaran('SRT1', 50000, 'Beli sensor ultrasonic');    